### ISSUE TITLE
TypeError: Error thrown in hooked function '' for hook 'renderChatMessage'. Cannot read properties of null (reading 'substr')

### ISSUE THREAD

**Issue by Acheronx98** [xdy/xdy-pf2e-workbench#1144]
Hi there,

I'm getting an error when attempting to use the `game.PF2eWorkbench.basicActionMacros()` macro.

Foundry Version: v11.315
PF2e Version: v5.10.3
PF2e Workbench Version: v5.35.3

```
<player> tries to remember if they've heard something related to this.
commons.js:8807 

Foundry VTT | Created ChatMessage with id [EAZcTidm42YC4hOm]
foundry.js:733 

Foundry VTT | Error thrown in hooked function '' for hook 'renderChatMessage'
#call @ foundry.js:733
call @ foundry.js:712
getHTML @ foundry.js:20720
await in getHTML (async)
getHTML @ pf2e.mjs:1601
await in getHTML (async)
postOne @ foundry.js:85744
_onCreate @ foundry.js:20813
_onCreate @ pf2e.mjs:1601
callback @ foundry.js:13603
(anonymous) @ foundry.js:13576
#handleCreateDocuments @ foundry.js:13576
await in #handleCreateDocuments (async)
_createDocuments @ foundry.js:13437
await in _createDocuments (async)
create @ commons.js:8629
await in create (async)
createDocuments @ commons.js:7958
create @ commons.js:8081
eval @ VM523837:256
await in eval (async)
#executeScript @ foundry.js:22928
execute @ foundry.js:22876
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Macro.prototype.execute#advanced-macros @ main.js:53
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Macro.prototype.execute#0 @ libWrapper-wrapper.js:189
(anonymous) @ basicActionMacros.ts:772
Promise.then (async)
action @ basicActionMacros.ts:768
(anonymous) @ basicActionMacros.ts:827

foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'renderChatMessage'. Cannot read properties of null (reading 'substr')
    at calcHeaderTextColor (message-hooks.js:75:32)
    at themeHeader (message-hooks.js:44:22)
    at Object.fn (message-hooks.js:36:3)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at ChatMessagePF2e.getHTML (foundry.js:20720:11)
    at async ChatMessagePF2e.getHTML (pf2e.mjs:1601:22311)
    at async ChatLogPF2e.postOne (foundry.js:85744:18)
onError @ foundry.js:753
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:734
call @ foundry.js:712
getHTML @ foundry.js:20720
await in getHTML (async)
getHTML @ pf2e.mjs:1601
await in getHTML (async)
postOne @ foundry.js:85744
_onCreate @ foundry.js:20813
_onCreate @ pf2e.mjs:1601
callback @ foundry.js:13603
(anonymous) @ foundry.js:13576
#handleCreateDocuments @ foundry.js:13576
await in #handleCreateDocuments (async)
_createDocuments @ foundry.js:13437
await in _createDocuments (async)
create @ commons.js:8629
await in create (async)
createDocuments @ commons.js:7958
create @ commons.js:8081
eval @ VM523837:256
await in eval (async)
#executeScript @ foundry.js:22928
execute @ foundry.js:22876
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Macro.prototype.execute#advanced-macros @ main.js:53
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Macro.prototype.execute#0 @ libWrapper-wrapper.js:189
(anonymous) @ basicActionMacros.ts:772
Promise.then (async)
action @ basicActionMacros.ts:768
(anonymous) @ basicActionMacros.ts:827
```

![image](https://github.com/Dorako/pf2e-dorako-ui/assets/5783760/0f87be23-d9bb-435a-b817-1833a4826434)

**Comment by xdy** [comment]
Seems to work for me, both as GM and as player. Please try again with no other modules active (and make sure you are on at least workbench 5.36.0).

**Comment by xdy** [comment]
Haven't heard back so closing issue.
