### ISSUE TITLE
pf2e workbench would not pass the metadata validation (not even available in the module list in game)

### ISSUE THREAD

**Issue by Ddinistrioll** [xdy/xdy-pf2e-workbench#697]
Game hosted on the Forge, if this can help, Latest version of pf2e workbench and the pf2e system. Here's the log :

```
Metadata validation failed for module "xdy-pf2e-workbench": The file "lang/ru.json" included by module xdy-pf2e-workbench does not exist
Error: Metadata validation failed for module "xdy-pf2e-workbench": The file "lang/ru.json" included by module xdy-pf2e-workbench does not exist
at PackageAssetField.initialize (file:///opt/foundryvtt/dist/packages/package.mjs:1:1275)
at SchemaField.initialize (file:///opt/foundryvtt/common/data/fields.mjs:436:23)
at file:///opt/foundryvtt/common/data/fields.mjs:859:40
at Array.map (<anonymous>)
at SetField.initialize (file:///opt/foundryvtt/common/data/fields.mjs:859:18)
at SetField.initialize (file:///opt/foundryvtt/common/data/fields.mjs:910:26)
at Module._initialize (file:///opt/foundryvtt/common/abstract/data.mjs:196:27)
at new DataModel (file:///opt/foundryvtt/common/abstract/data.mjs:58:10)
at new BasePackage (file:///opt/foundryvtt/common/packages/base-package.mjs:61:5)
at new BaseModule (file:///opt/foundryvtt/common/packages/base-module.mjs:11:16)
```

**Comment by xdy** [comment]
This is fixed in 4.52.1 that was released an hour ago, try checking for a new version again in the forge (it sometimes takes a while for the forge to update.)
